### ISSUE TITLE
Multiple build issues

### ISSUE THREAD

**Issue by dolmen** [urfave/sflags#11]
I'm trying to build fdbe18cab49348fa0bbc857387bafd65a814aecb before starting to contribute, but:
### 1. `make` fails
```
$ make
Go generate
Formatting
Run vet
Run lint
Run metalinter
parser_test.go:28:3:warning: field name6 is unused (U1000) (megacheck)
make: *** [check] Error 1
```
I'm using the latest `gometalinter` and I have ensured that the linters are up-to-date (`gometalinter -i -u`)
### 2. `go test` fails
```
--- FAIL: TestValidator (0.00s)
        Error Trace:    parser_test.go:414
	Error:      	Invalid operation: (sflags.ValidateFunc)(nil) == (sflags.ValidateFunc)(nil) (cannot take func type as argument)
	Test:       	TestValidator
FAIL
exit status 1
FAIL	github.com/octago/sflags	0.025s
```
I'm using the latest version of the `assert` package: `go get -u github.com/stretchr/testify/assert`

**Comment by dolmen** [comment]
The first issue can be fixed by adding the following line in `parser_test.go`:
```go
_ = simpleCfg.name6
```

**Comment by m0sth8** [comment]
@dolmen thank you, I fixed tests and metalinter issues. Also, I added weekly jobs in travis.
