### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by ixdy** [urfave/sflags#22]
There have been a number of new features and bug fixes since the last tagged release, v0.2.0:
https://github.com/octago/sflags/compare/v0.2.0..master

Can we tag a new release to simply updates for projects using `go mod`?

**Comment by m0sth8** [comment]
Hi @ixdy ,

Thank you for suggestion.
I've just released a new v0.3.0 version.

**Comment by ixdy** [comment]
Thanks!
